In [1]:
import numpy as np

In [6]:
print(np.__version__)

1.19.3


In [2]:
l=[i for i in range(11)]
a=np.array(l)            #1D array
print(a)
b=np.array([[1,2,3,4],[5,6,7,8]])          #2D array
print(b)
c=np.array([[1,2,3],[4,5,6],[7,8,9]])      #3D array
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
2


In [4]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [5]:
print(a.shape)
print(b.shape)
print(c.shape)

(11,)
(2, 4)
(3, 3)


In [7]:
print(len(a))
print(len(b))
print(len(c))

11
2
3


In [10]:
print(a)
print(a[:-1])
print(a[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1  0]


In [22]:
print(b)
print()
print(b[0])
print()
print(b[0][0])
print()
print(b[0][:2])
print()
print(b[:,:2])

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]

1

[1 2]

[[1 2]
 [5 6]]


In [21]:
print(c)
print()
print(c[0])
print()
print(c[1][:2])
print()
print(c[2][:])
print()
print(c[:2,:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[4 5]

[7 8 9]

[[1 2]
 [4 5]]


In [23]:
print(a)
print()
x=a.copy()        #use computer memory
y=a.view()        #does not use computer memory
print(x)
print()
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  1  2  3  4  5  6  7  8  9 10] [ 0  1  2  3  4  5  6  7  8  9 10]


In [25]:
print(b)
print()
x=b.copy()        #use computer memory
y=b.view()        #does not use computer memory
print(x)
print()
print(y)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
print(c)
print()
x=c.copy()      #use computer memory
y=c.view()      #does not use computer memory
print(x)
print()
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(a)
print()
for i in a:
    print(i,end=" ")
print()
print()
for i in range(len(a)):
    print(a[i],end=" ")

[ 0  1  2  3  4  5  6  7  8  9 10]

0 1 2 3 4 5 6 7 8 9 10 

0 1 2 3 4 5 6 7 8 9 10 

In [35]:
print(b)
print()
for i in b:
    print(i,end=" ")
print()
print()
for i in range(len(b)):
    print(b[i],end=" ")
print('\n\n')    
#element by element
for i in b:
    for j in i:
        print(j,end=" ")

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4] [5 6 7 8] 

[1 2 3 4] [5 6 7 8] 


1 2 3 4 5 6 7 8 

In [42]:
x=a.view()
print(a)
print()
print(x)
print()
c=np.zeros(11)
for i in range(len(x)):
    if a[i]%2!=0:
        c[i]=a[i]+x[i]
    else:
        c[i]=a[i]
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0  1  2  3  4  5  6  7  8  9 10]

[ 0.  2.  2.  6.  4. 10.  6. 14.  8. 18. 10.]


In [46]:
#addition of 2D matrix 
x=b.view()
print(b)
print()
print(x)
print()
c=np.zeros((2,4))
f=x.shape
for i in range(f[0]):
    for j in range(f[1]):
        if b[i][j]%2!=0:
            c[i][j]=b[i][j]+x[i][j]
        else:
            c[i][j]=b[i][j]
print()
print(c)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]


[[ 2.  2.  6.  4.]
 [10.  6. 14.  8.]]


In [9]:
#Reshaping the data into row and column
l=[i for i in range(1,11)]
a=np.array(l).reshape(2,5)
b=np.array(l).reshape(5,2)
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [11]:
#To iterate through all element by using single loop
#nditer()
for i in np.nditer(b):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [13]:
#To multiply the matrix 
#3 ways(normal mathematics,dot function and @ character)
#normal mathematics
a=[[1,2,3],[4,5,6]]
b=a
c=[[0 for i in range(3)] for i in range(2)]
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            c[i][j]=a[i][k]+b[k][j]
            
print(c)            

[[6, 7, 8], [9, 10, 11]]


In [15]:
#dot function
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
c=np.dot(a,b)
print(c)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [18]:
#@ character
a=np.array([[1,1],[2,2]])
b=np.array([[3,3],[4,4]])
c=a @ b
print(c)

[[ 7  7]
 [14 14]]


In [25]:
#Concatenate 1D array
a=np.arange(2,20,2)
b=np.arange(1,20,2)
c=np.concatenate((a,b))
print(c)

[ 2  4  6  8 10 12 14 16 18  1  3  5  7  9 11 13 15 17 19]


In [27]:
#Concatenate 1D array
even=[i for i in range(2,20,2)]
odd=[i for i in range(1,20,2)]
a=np.array(even)
b=np.array(odd)
c=np.concatenate((a,b))
print(c)

[ 2  4  6  8 10 12 14 16 18  1  3  5  7  9 11 13 15 17 19]


In [29]:
#Concatenate 2D array
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.concatenate((a,b))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#Concatenate 2D array in one row by using axis=1
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.concatenate((a,b),axis=1)
print(c)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [39]:
#stack function in 1D function
a=np.zeros((5))
b=np.ones((5))
c=np.stack((a,b))
print(c)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [40]:
#stack function in 1D function using axis=1
a=np.zeros((5))
b=np.ones((5))
c=np.stack((a,b),axis=1)
print(c)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [41]:
#Stack function in 2D array 
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.stack((a,b))
print(c)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [33]:
#Stack function in 2D array in one row (axis=1) 
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.stack((a,b),axis=1)
print(c)

[[[0. 0. 0.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [1. 1. 1.]]]


In [42]:
#vertical stack in 1D array
a=np.zeros((5))
b=np.ones((5))
c=np.vstack((a,b))
print(c)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [43]:
#horizontal stack in 1D array
a=np.zeros((5))
b=np.ones((5))
c=np.hstack((a,b))
print(c)

[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]


In [44]:
#Vertical stack in 2D array
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.vstack((a,b))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [45]:
#Horizontal stack in 2D array
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.hstack((a,b))
print(c)

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [47]:
#D Stack 1D array using
a=np.zeros((5))
b=np.ones((5))
c=np.dstack((a,b))
print(c)

[[[0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]
  [0. 1.]]]


In [48]:
#D stack in 2D array
a=np.zeros((2,3))
b=np.ones((2,3))
c=np.dstack((a,b))
print(c)

[[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]


In [49]:
#Spliting the 1D array
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.array_split(a,3)
print(b)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [50]:
#Spliting the 2D array
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b=np.array_split(a,3)
print(b)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([], shape=(0, 5), dtype=int32)]


In [52]:
#Spliting the 3D array
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b=np.array_split(a,3)
print(b)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]])]


In [53]:
#spliting the array 2D (along the rows)
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
x=np.array_split(a,3,axis=1)
print(x)

[array([[ 1,  2],
       [ 6,  7],
       [11, 12]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14]]), array([[ 5],
       [10],
       [15]])]


In [54]:
for i in x:
    print(i)

[[ 1  2]
 [ 6  7]
 [11 12]]
[[ 3  4]
 [ 8  9]
 [13 14]]
[[ 5]
 [10]
 [15]]


In [59]:
#searching the array 1D
a=np.array([1,2,3,4,5,1,0])
c=np.where(a==1)
print(c)
#returns in tuple form
for i in c[0]:
    print(i,end=" ")

(array([0, 5], dtype=int64),)
0 5 

In [60]:
#Searching through sorted array
a=np.array([1,6,3,2,5,4])
c=np.searchsorted(a,5)
print(c)

6


In [64]:
#Searching through sorted array (right side)
#basically it sorted the array from right side
a=np.array([1,6,3,2,5,4])
c=np.searchsorted(a,2,side='right')
print(c)

4


In [67]:
#Sorting the 1D array
a=np.array([1,6,3,2,5,4])
a.sort()
print(a)

[1 2 3 4 5 6]


In [69]:
#Sorting the 2D array
a=np.array([[1,6,3,2,5,4],[1,6,3,2,5,4]])
a.sort()
print(a)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [71]:
#Filtering the array 1D
a=np.array([1,6,3,2,5,4])
a.sort()
x=[True,False,False,True,True,False]
c=a[x]
print(c)

[1 4 5]


In [74]:
#Filtering odd elements
a=np.array([1,6,3,2,5,4])
a.sort()
l=[]
for i in a:
    if i%2!=0:
        l.append(True)
    else:
        l.append(False)
c=a[l]
print(c)

[1 3 5]


In [75]:
#Filtering even elements
a=np.array([1,2,3,4,5,6])
l=[]
for i in a:
    if i%2==0:
        l.append(True)
    else:
        l.append(False)
c=a[l]
print(c)

[2 4 6]


In [2]:
#Random lib in numpy
from numpy import random

In [ ]:
#Difference between True random number and pseudo random number is that 
#True random number use an unpredixtable physical means to generate numbers(atmospheric noise)
#Pseudo random number uses mathematical algorithms(completely computer generated)

In [83]:
#We can generate truly random number by using random data
a=random.randint(100)                        #integer value
print(a)

67


In [88]:
#Float Value 
a=random.rand()
print(a)

0.43487403469483865


In [93]:
#Creating list of random numbers (1D array)
a=random.randint(100,size=(5))
print(a)

[12 91 44 47 34]


In [99]:
#Creating 2D array of random numbers
a=random.randint(100,size=(2,3))
print(a)

[[ 5 87 58]
 [64  5 90]]


In [104]:
#Choice function (to choose random number from the 1D array)
a=random.choice([1,2,3,4,5,6])
print(a)

4


In [108]:
#Choice function (creating 2D array from a 1D array)
a=random.choice([1,2,3,4,5,6],size=(2,3))
print(a)

[[3 2 5]
 [5 5 5]]


In [4]:
#Giving the probability for every number
a=random.choice([1,2,3,4,5,6],p=[0.1,0.1,0.1,0.2,0.1,0.4],size=(3,3))
print(a)

[[3 2 2]
 [6 6 6]
 [4 1 5]]


In [5]:
#Zero Probability example
a=random.choice([1,2,3,4,5,6],p=[0.2,0.2,0.2,0.2,0.2,0],size=(3,3))
print(a)

[[2 3 1]
 [5 2 3]
 [4 3 3]]


In [6]:
#Permutation 
#permutation of 0 1 is 01 10 (2 permutation)
#Without using permutation function
a=np.array([1,2,3,4,5])
random.shuffle(a)
print(a)

[3 4 1 2 5]


In [7]:
#Permutation function
a=np.array([1,2,3,4,5])
print(random.permutation(a))

[5 1 2 3 4]
